### ISSUE TITLE
Flashing bootloader to gap8 hangs

### ISSUE THREAD

**Issue by Laatikk01234** [bitcraze/aideck-gap8-bootloader#3]
Hi,

I am trying to flash the bootloader onto aideck.

With command
aideck-gap8-bootloader$ sudo docker run --rm -it -v $PWD:/module/ --device /dev/ttyUSB0 --privileged -P bitcraze/aideck:4.8.0.1 /bin/bash -c 'export GAPY_OPENOCD_CABLE=interface/ftdi/olimex-arm-usb-tiny-h.cfg; source /gap_sdk/configs/ai_deck.sh; cd /module/;  make clean all image flash'

Running the docker container hangs execution on step: Load image done

Flashing image with command:
gap8-openocd -d0 -c "gdb_port disabled; telnet_port disabled; tcl_port disabled" -c "script interface/ftdi/olimex-arm-usb-tiny-h.cfg; script target/gap8revb.tcl; script tcl/flash_image.tcl; script tcl/jtag_boot.tcl; gap_flash_raw_hyper /module/BUILD/GAP8_V2/GCC_RISCV_FREERTOS/target.board.devices.flash.img 75808 /gap_sdk/utils/openocd_tools; exit;"
Open On-Chip Debugger 0.10.0+dev-gb84d97ec4 (2022-04-14-06:44)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 0

DEPRECATED! use 'adapter speed' not 'adapter_khz'
DEPRECATED! use 'adapter driver' not 'interface'
TARGET create
GAP8 INIT TARGET
GAP8 examine target
Init jtag
Initialising GAP8 JTAG TAP
--------------------------
begining flash session (hyperflash)
--------------------------
load flasher to L2 memory
Loading binary through JTAG
[Flahser]: Hyperflash flasher is ready
Instruct flasher to begin flash per se
device struct address is 470047192
going to wait on addr GAP_RDY
wait on gap_rdy done witg buff ptr 0 469784844
loading image with addr 469784844 addr_min 469784844 and size 75808
load image done

**Comment by evoggy** [comment]
Hi!

Have you managed to flash other firmware for the GAP8 before on this deck?

**Comment by Laatikk01234** [comment]
Hi,

Not on the GAP8

Flashing the esp worked fine.

------------------
On a further note:
I had a spare aideck and I used the same guide to flash it and that did work.
So I am tempted to say that the chip itself would be broken.


Next hiccup i got following the wifi-streaming tutorial was flashing the gap8-firmware with the bootloader
I got this kind of magic

aideck-gap8-examples$ cfloader flash examples/other/wifi-img-streamer/BUILD/GAP8_V2/GCC_RISCV_FREERTOS/target.board.devices.flash.img deck-bcAI:gap8-fw -w radio://0/80/2M
Reset to bootloader mode ...
Could not save cache, no writable directory
Could not save cache, no writable directory
Version 3 not supported

But on even further note the aideck wifi was working and i managed to flash the firmware through it and everything is working for the moment.

**Comment by evoggy** [comment]
Seems like there might be an issue with the hardware, drop us an email at support@bitcraze.io and we'll sort it out.

For the second issue, we haven't had the time to release the newest version of the crazyflie-python-library with the updated support, so if you would like to use this feature you need to clone the latest lib and install that. Here's some instructions: https://github.com/bitcraze/crazyflie-lib-python/blob/master/docs/installation/install.md#developing-for-the-cflib
